### ISSUE TITLE
Create Welcome Page

### ISSUE THREAD

**Issue by steveasher** [teamup-org/mern-template#5]
This page is a Teamup-branded Welcome Page. It can talk a little about Teamup. It can also help someone new to the project orient themselves and get started quickly.

**Comment by radhika-srinivasan** [comment]
https://www.figma.com/design/uTJBFt9NfzmcfFRKtHSthS/Solo-webpage?node-id=0-1&t=Oen7naGxmSgeA84G-0

**Comment by radhika-srinivasan** [comment]
The content for the webpage is here https://docs.google.com/document/d/10CaEwhDn9QOjlbikHRjydU8x38qupYK9UfcYXGEEnf8/edit?usp=sharing
